# Generated by Django 4.2.2 on 2023-06-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=20, verbose_name='RUT'),
        ),
    ]
